Aperture: Depend on okio-jvm
Fixes:
java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;

Test: Take a photo and look at gallery button icon
Change-Id: I3977dbfcaf4d60be9d41989af839c06b20dc3738